version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    nuget install ILRepack -ExcludeVersion

    ILMerge\tools\ilmerge.exe /internalize /out:Indentional\Indentional.dll Indentional\bin\Release\netstandard1.1\Indentional.dll Indentional\bin\Release\netstandard1.1\ShinySwitch.dll

    dotnet pack Indentional\Indentional.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: rTAOxhsBekNlEb9IN6Iyy5mayYbiTTIWidYKB4f1ZyRbwiIeqjFr0x6qDZQM6RYP